### ISSUE TITLE
将文件格式从markdown换为org后的一些小问题

### ISSUE THREAD

**Issue by AllTheLife** [xhcoding/emacs-aichat#1]
1. 第一次提问生成的回答是一级标题，后来就是二级标题
如：
``` org
* 你好
你好，这里是必应。我可以用中文和你交流。😊

** 你如何看待这个项目：https://github.com/xhcoding/emacs-aichat
这个项目是一个在Emacs中使用必应人工智能聊天的插件[^1^]。它可以让你用Emacs和我对话，就像你现在在手机上做的一样。😊 
```
2. 不会再显示信息来源的url

大佬加油！

**Comment by xhcoding** [comment]
我把默认的格式改成 markdown 了，用 org-mode 需要将接口返回的信息从 md 的格式转成 org，可能会有比较多的问题。org-mode 还是支持的

第一次提问相当与开启了新的会话，后面的提问都是同一个会话，所以我将后面的提问改成二级标题，表示后面的问题和第一个问题相关。

信息来源的 url 现在显示在最后了
