### ISSUE TITLE
Option to use Org format instead of Markdown

### ISSUE THREAD

**Issue by MunsterPlop** [xhcoding/emacs-aichat#12]
I think it would be nice to be able to generate an Org buffer instead of a Markdown one adding an option such as `aichat-bingai-chat-file-format` which could accept `'org` and `'markdown`.

It could also exist for the other backend `aichat-openai-chat-file-format`.

**Comment by xhcoding** [comment]
You can define `aichat-bingai-chat-file` as an org file, but please note that I used a simple function to convert some markdown tags to org format, so there may be some tags that are not handled yet.
