### ISSUE TITLE
binai-chat, binai-assisstant, and openai-chat don't work: seems to be getting bad output in curl filter data

### ISSUE THREAD

**Issue by armindarvish** [xhcoding/emacs-aichat#13]
I am on emacs29 and macOS and have been trying to use this package and I am having issues. Basically, **the only thing that works right now is openai-assistant. The other functions don't work**:

## bingai-chat does not return responses and get stuck on "Replying...:
<img width="1050" alt="Screenshot 2023-04-11 at 8 11 40 AM" src="https://user-images.githubusercontent.com/18317557/231207843-286ddac8-4c69-43b8-82d3-2dc2deb027aa.png">

### I checked the debug buffer. The login seems to be working fine, the curl data filter is not:
<img width="1388" alt="Screenshot 2023-04-11 at 7 59 52 AM" src="https://user-images.githubusercontent.com/18317557/231207109-e54c42e6-d8cd-4c92-a83f-58a5484dd437.png">

## openai-chat also gets stuck without any response:
<img width="806" alt="Screenshot 2023-04-11 at 8 13 27 AM" src="https://user-images.githubusercontent.com/18317557/231208272-2c4240f5-d97c-4174-b39b-68a29f078ce8.png">

### The debug buffer again shows some weird response in curl data filter:
<img width="969" alt="Screenshot 2023-04-11 at 8 16 50 AM" src="https://user-images.githubusercontent.com/18317557/231209327-66084317-7309-498c-a82b-a4e9c393c205.png">

### bingai-assistant does not open a buffer! and the curl data filter is exactly the same as bingai-chat above

**Comment by xhcoding** [comment]
You can choose to use `url` backend. I don't have macOS, so I can't reproduce the problem. I'll try to reproduce it in a virtual machine when I have time.

```lisp
(setq aichat-http-backend 'url)
```
