### ISSUE TITLE
MELPA / Straight version?

### ISSUE THREAD

**Issue by liar666** [xhcoding/emacs-aichat#16]
You package is more interesting to me than org-ai, as it allows to use the "free" bingchat

But it would be great to have a MELPA/straight version so that it is easier to install & maintain.

**Comment by xhcoding** [comment]
You can use straight :
```elisp
  (use-package emacs-aichat
    :straight (emacs-aichat :type git :host github :repo "xhcoding/emacs-aichat"))
```
