### ISSUE TITLE
Get images

### ISSUE THREAD

**Issue by liar666** [xhcoding/emacs-aichat#18]
Hello,

Thanks for the tool, it's very neat to have that in Emacs!!!

BingChat can now generate images. Unfortunately, they do not appear in `aichat-bingai-assistant-buffer` :'(

**Comment by xhcoding** [comment]
Now bingai can [generate images in assistant buffer](https://github.com/xhcoding/emacs-aichat/commit/50b8fea34431d771855197ce13cf62f8784492c0)
