### ISSUE TITLE
websocket问题

### ISSUE THREAD

**Issue by luyajun01** [xhcoding/emacs-aichat#19]
您好：
最近在使用的时候，出现如下问题：

```
﻿(error Chathub unexpected closed during handshake.) 
﻿ ■  Error (websocket): in callback `on-open': Error response received from websocket server: 403

```

**Comment by xhcoding** [comment]
可能需要开代理才行

**Comment by luyajun01** [comment]
> 可能需要开代理才行

应该不是，之前用过这个包的。代理啥的没啥问题的

**Comment by xhcoding** [comment]
之前建立 websocket 连接对话是不需要代理的，现在不行了。 而且 emacs 的 websocket 插件不支持单独设置代理，所以只能用全局的代理。Linux 上可以用 proxychains 代理整个 emacs

**Comment by xhcoding** [comment]
最新的 commit 让 websocket 插件支持单独设置代理，只要设置 aichat-bingai-proxy 就能工作了，不再需要全局代理
