### ISSUE TITLE
Bing AI Produces Gibberish

### ISSUE THREAD

**Issue by ziova** [xhcoding/emacs-aichat#25]
This majorly happens when Bing searches the internet. The output looks something like this:

![image](https://github.com/xhcoding/emacs-aichat/assets/79858886/d2f98611-ce98-4ded-a18e-f8f189797052)

it looks as if it is returning what it is researching. Is there any fix? is this a problem with the scraper?

**Comment by xhcoding** [comment]
I don't have any relevant issues here, please refer to the methods provided in the following link and attach the relevant logs: https://github.com/xhcoding/emacs-aichat#feedback-issues

**Comment by orcalover45** [comment]
Here is the debug output: https://0x0.st/H_QX.txt

Also, something to note is that the aichat works fine when the model is set on "Balanced". This error is only caused when the model is on "creative".

**Comment by ziova** [comment]
Commit 8647a6b fixes the problem thus closing this issue.
