### ISSUE TITLE
Interested in joining forces?

### ISSUE THREAD

**Issue by freckletonj** [xhcoding/emacs-aichat#27]
Hi, I'm the author of [UniteAI](https://github.com/freckletonj/uniteai), and I like what you're working on. My project is similar but doesn't have Bing support, nor image support yet. The major difference is, I'm using a python backend so that any editor can use it (via LSP), and so that its easy to add any model (such as speech-to-text, image gen, document embeddings, etc.)

I'd be curious for your feedback on UniteAI, and I'd love to join forces. We could start a discord or something and coordinate. If you're interested :)

**Comment by xhcoding** [comment]
I'm sorry, I don't have time to participate recently. Thank you for your invitation.

If you want to add Bing support to your project, you can refer to  [ EdgeGPT.](https://github.com/acheong08/EdgeGPT)

**Comment by freckletonj** [comment]
Thanks for the tip!

And we've started a discord, if you ever want to keep a pulse on this project: https://discord.gg/3K2Q93bug
