### ISSUE TITLE
Please publish on melpa

### ISSUE THREAD

**Issue by port19x** [xhcoding/emacs-aichat#29]
Could you please publish the package on melpa so it's possible to install this with the default facilities for package management present in emacs?
I'm not setting up a different package manager for bing chat.
It also enhances the marketability of the project if installation instructions can be reduced to a `(use-package emacs-aichat)`

*yes, I'm aware this is a duplicate of #16*

**Comment by xhcoding** [comment]
I don’t want to risk putting the package on melpa, because bing chat might violate Microsoft’s terms of service, and it might stop working at any time.
