### ISSUE TITLE
Unauthorized Request: Conversation Signature is not set

### ISSUE THREAD

**Issue by ziova** [xhcoding/emacs-aichat#30]
Emacs AIChat's bing version has been broken and gives this error: 

![image](https://github.com/xhcoding/emacs-aichat/assets/79858886/05a8a5bb-113a-4a06-92c0-21f8c9658cec)

**Comment by xhcoding** [comment]
I have updated bingai , you can update the latest code and give it a try

**Comment by ziova** [comment]
Tried and it works, closing this issue. Thank you!
