### ISSUE TITLE
ChatHub not authorized

### ISSUE THREAD

**Issue by hvzzzz** [xhcoding/emacs-aichat#31]
I just made a fresh installation on Doom Emacs using
`
(package! aichat-bingai
  :recipe (:host github
           :repo "xhcoding/emacs-aichat"
           :files ("aichat-bingai.el" "*.el")))
`
Emacs AIChat's Bing gives the following error
![image](https://github.com/xhcoding/emacs-aichat/assets/42120805/d12983a6-6390-43f0-9618-08a3a163294f)

**Comment by Feyrbrand** [comment]
I followed the same installation instructions and also got the same error.

Both options resulted in the same ChatHub not authorized error message.

**Comment by xhcoding** [comment]
Please attach running logs:   https://github.com/xhcoding/emacs-aichat#feedback-issues

**Comment by Feyrbrand** [comment]
I'm sorry, here they are :)

[errorlog.txt](https://github.com/xhcoding/emacs-aichat/files/13177971/errorlog.txt)

**Comment by xhcoding** [comment]
you can update the latest code and give it a try

**Comment by hvzzzz** [comment]
Hi, Now it is working, thank you. Amazing work!

**Comment by Feyrbrand** [comment]
Yeah, it works now, I just can't use a space separator in the minibuffer to write my questions, but maybe thats an emacs problem :)

Ty
