### ISSUE TITLE
error UnauthorizedRequest:The conversationSignature is not set and is required to ensure that you have permission to use our APIs.

### ISSUE THREAD

**Issue by liar666** [xhcoding/emacs-aichat#32]
Hi,

My "cookies.json" was not working anymore, so I extracted it again with "Cookie Editor".

And now I get the following error:
```
Error: (error UnauthorizedRequest:The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=
```

**Comment by xhcoding** [comment]
Try to update to the latest version



------------------ Original ------------------
From: G. M. ***@***.***&gt;
Date: Wed,Nov 8,2023 5:59 PM
To: xhcoding/emacs-aichat ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [xhcoding/emacs-aichat] error UnauthorizedRequest:TheconversationSignature is not set and is required to ensure that you havepermission to use our APIs. (Issue #32)





 
Hi,
 
My "cookies.json" was not working anymore, so I extracted it again with "Cookie Editor".
 
And now I get the following error:
 Error: (error UnauthorizedRequest:The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=

**Comment by liar666** [comment]
I got the lastest version from straight today (`aichat.el` says `version 0.1`).
Got the exact same error
.

**Comment by xhcoding** [comment]
Maybe you should update to the latest commit, look https://github.com/xhcoding/emacs-aichat/issues/30

**Comment by liar666** [comment]
I don't know why I switched my configuration to use the straight version instead of the local copy of your repo.

It now works again. Thanks !
