### ISSUE TITLE
Parse open-ai key without auth-source-pick-first-password, instead provide an option to have a file in which the key can be kept or simply typing the key in using plain text

### ISSUE THREAD

**Issue by niv-dev** [xhcoding/emacs-aichat#9]

**Comment by MunsterPlop** [comment]
I believe this should be an option.
Something like `aichat-use-auth-source` which, in my opinion, should be `t` by default for security reasons.
Storing the key in plain text isn't a good idea.

**Comment by xhcoding** [comment]
You can use any text file, such as `path/a.txt`, just fill in the api key according to the autoinfo format and add the path to `auth-sources`.

a.txt
```
machine platform.openai.com login aichat-openai password xxx
```

add `a.txt` to `auth-sources`

```
(add-to-list 'auth-sources "path/a.txt")
```
